// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikvflzzeeygozlslikfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdmZsenplZXlnb3psc2xpa2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTY3OTQsImV4cCI6MjA3MjIzMjc5NH0.BOBfmwNC-hfNjvqU3axnk5KEM3H6xg9mX0S1cc9B6PE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});